In [ ]:
#Import Libraries & Load the Dataset
import pandas as pd

# Load the dataset
df = pd.read_csv("/content/archive.zip")

# Basic info
print("Shape:", df.shape)
df.head()

Shape: (5837, 12)

,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type,show_id
0,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show,81193313/
1,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie,81197050/
2,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie,81213894/
3,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie,81082007/
4,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show,80213643/

In [ ]:
# Count missing values in each column
print(df.isnull().sum())

# Option 1: Drop rows with missing values
df_cleaned = df.dropna()

title              0
director        1901
cast             556
country          427
date_added       642
release_year       0
rating            10
duration           0
listed_in          0
description        0
type               0
show_id            0
dtype: int64

In [ ]:
# Check for duplicate rows
print("Duplicates:", df_cleaned.duplicated().sum())

# Drop duplicates if any
df_cleaned = df_cleaned.drop_duplicates()

Duplicates: 0

In [ ]:
# Convert 'type' and 'country' to lowercase and strip whitespace
df_cleaned['type'] = df_cleaned['type'].str.lower().str.strip()
df_cleaned['country'] = df_cleaned['country'].str.lower().str.strip()

In [ ]:
# Convert 'date_added' to datetime format
df_cleaned['date_added'] = pd.to_datetime(df_cleaned['date_added'], errors='coerce')

In [ ]:
# Rename all columns to lowercase and replace spaces with underscores
df_cleaned.columns = df_cleaned.columns.str.lower().str.replace(' ', '_')

In [ ]:
# Check column data types
print(df_cleaned.dtypes)

# Fix types if needed (example: release_year should be int, date_added is datetime)
df_cleaned['release_year'] = df_cleaned['release_year'].astype(int)

title                   object
director                object
cast                    object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
description             object
type                    object
show_id                 object
dtype: object

In [ ]:
df_cleaned.to_csv("cleaned_netflix_dataset.csv", index=False)